### ISSUE TITLE
About sample weights and scale estimation

### ISSUE THREAD

**Issue by gzpan** [martin-danelljan/ECO#2]
I would like to know why CCOT and ECO do not use adaptive decontamination strategy as SRDCF_decon do and scale estimation as fDSST do? Isn't SRDCF_decon an effective method to solve the problem of model update? Though scale estimation strategy from fDSST is included in ECO, it is not used in OTB and VOT test. I am confusing.

**Comment by martin-danelljan** [comment]
When we develop our trackers, we prefer to keep things simple and transparent. Although the decontamination approach, which is quite general, can give a boost in performance, it was not necessary for CCOT and ECO in order to demonstrate their effectiveness. The decontamination CVPR 2016 paper is an independent contribution that can easily be integrated in either of these two. In fact, the code in CCOT and ECO are already prepared for that.

**Comment by gzpan** [comment]
Oh I see. thanks! I want to say that you always do the right thing in tracking. Hope keeps it and contribute more elegant ideas to tracking(CV) community.

**Comment by martin-danelljan** [comment]
Thank you for your kind words! :D
