### ISSUE TITLE
ECO tracking source code issue

### ISSUE THREAD

**Issue by ucassdlfj** [martin-danelljan/ECO#36]
![image](https://user-images.githubusercontent.com/24973046/42258663-7006cdea-7f8f-11e8-9cff-976b0d202cf9.png)

**Comment by Superlee506** [comment]
@ucassdlfj Hi, do you solve this problem?

**Comment by ucassdlfj** [comment]
@Superlee506 Not yet, I don't know whether my thought are correct. But after I change the codes in mat-file './implementation/training/lhs_operation_gpu.m'  in my way. CG methods also converge！So I'm a little confused about it,maybe I was wrong about that. I wonder if you have ever thought about this? Maybe we can share some deeper thought about it !

**Comment by martin-danelljan** [comment]
Hi. Sorry for the delay of my response. But I hope it will still be useful for you.

If I understand you question correctly, the answer is basically this:
What you propose is to learn the filters independently. This is also perfectly fine, and could in fact be beneficial some times (see our most recent [ECCV 2018 paper](https://arxiv.org/abs/1804.06833). However, in ECO (and CCOT) the filter are learned jointly. In fact, there are not three different label functions y, they are constructed with the same parameters. This is just a practical implementation detail, i.e. that I pre-extract the relevant Fourier coefficients for each feature block (resolution) to speed up the conjugate gradient. So if you did the corresponding modification of what you suggested, the CG and learning should still work since the filter are optimized independently.

**Comment by ucassdlfj** [comment]
Hi. I figure out myself later. But thanks your reply anyway. I  take it for granted that filters are learned independently in ECO (and CCOT) when I first read ECO paper and codes(which is more reasonable according to my intuition). To be honestly, your code are a little confusing to me, I read UPDT recently and truly two methods of filter learning are all fine.
