### ISSUE TITLE
Some questions about the "Scale filter"

### ISSUE THREAD

**Issue by Superlee506** [martin-danelljan/ECO#37]
Hi, when I compare the 'fdsst' code with 'dsst' code， I find that 

The value of ys is： 
[1	0.642167199144790	0.170056201828270	0.0185709050136830	0.000836315026159023	1.55311269123150e-05	1.18941188747878e-07	3.75627879293239e-10	4.89192285304428e-13	4.89192285304428e-13	3.75627879293239e-10	1.18941188747878e-07	1.55311269123150e-05	0.000836315026159023	0.0185709050136830	0.170056201828270	0.642167199144790]  
The largest value is the first value. 

However in DSST code, the largest value is in the middle.  As to the transformation filter, the largest value is also different in the both codes.  Any suggestion would be appreciated. 

    ```
scale_exp = (-floor((nScales-1)/2):ceil((nScales-1)/2)) * nScalesInterp/nScales;
    scale_exp_shift = circshift(scale_exp, [0 -floor((nScales-1)/2)]);
    
    interp_scale_exp = -floor((nScalesInterp-1)/2):ceil((nScalesInterp-1)/2);
    interp_scale_exp_shift = circshift(interp_scale_exp, [0 -floor((nScalesInterp-1)/2)]);
    
    scaleSizeFactors = scale_step .^ scale_exp;
    interpScaleFactors = scale_step .^ interp_scale_exp_shift;
    
    ys = exp(-0.5 * (scale_exp_shift.^2) /scale_sigma^2);
```

**Comment by martin-danelljan** [comment]
Hi. Yes, since the image (or signal) is seen as periodic, it does not matter where you put the center. You just need to be sure to shift everything in that case. However, it becomes more convenient I think to put the origin of the output in coordinate (0,0) (or (1,1) in matlab), especially when the spatial regularization comes into play. You should think of the output as being in translation space instead of image space, and that the origin is in the upper left coordinate.
